pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                script {
                    // Pull the Docker image
                    sh 'sudo docker pull cirrusci/flutter:stable'
                    // Run the Docker container and execute Flutter commands
                    sh '''
                        sudo docker run -u root:root \
                        -v ${WORKSPACE}:/workspace \
                        cirrusci/flutter:stable /bin/bash -c "
                        cd /workspace/quiz_learn_app_ai && \
                        flutter doctor -v && \
                        flutter pub get && \
                        flutter test && \
                        flutter build apk --release"
                    '''
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'quiz_learn_app_ai/build/app/outputs/flutter-apk/app-release.apk', fingerprint: true
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
