pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'cirrusci/flutter:stable'
        APP_DIR = 'quiz_learn_app_ai'
        APK_PATH = 'build/app/outputs/flutter-apk/app-release.apk'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the Git repository
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                script {
                    // Pull the Flutter Docker image and run the build and test commands inside the container
                    docker.image(DOCKER_IMAGE).inside('-u root:root') {
                        dir(APP_DIR) {
                            // Run Flutter commands inside the Docker container
                            sh 'flutter doctor -v'
                            sh 'flutter pub get'
                            sh 'flutter test'
                            sh 'flutter build apk --release'
                        }
                    }
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive the generated APK as an artifact
                archiveArtifacts artifacts: "${APP_DIR}/${APK_PATH}", fingerprint: true
            }
        }
    }

    post {
        always {
            // Clean the workspace after the build
            cleanWs()
        }
    }
}
