pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Flutter and Android SDK') {
            steps {
                sh '''
                    # Install necessary packages
                    apt-get update
                    apt-get install -y wget unzip yes

                    # Remove existing Flutter and Android SDK directories if they exist
                    rm -rf flutter android-sdk
                    
                    # Clone the Flutter repository
                    git clone https://github.com/flutter/flutter.git -b stable
                    export PATH="$PATH:`pwd`/flutter/bin"
                    
                    # Install Flutter
                    flutter precache
                    flutter doctor

                    # Download and install Android SDK
                    ANDROID_SDK_ROOT=`pwd`/android-sdk
                    mkdir -p $ANDROID_SDK_ROOT
                    cd $ANDROID_SDK_ROOT
                    wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
                    unzip commandlinetools-linux-6609375_latest.zip
                    mkdir -p cmdline-tools/latest
                    mv cmdline-tools/* cmdline-tools/latest/
                    export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
                    yes | sdkmanager --licenses
                    sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
                    
                    # Set up environment variables
                    export ANDROID_HOME=$ANDROID_SDK_ROOT
                    export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
                    export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/30.0.3
                    flutter doctor --android-licenses
                    flutter doctor
                '''
            }
        }

        stage('Build') {
            steps {
                dir('quiz_learn_app_ai') {
                    sh '''
                        export PATH="$PATH:`pwd`/../flutter/bin"
                        export ANDROID_HOME=`pwd`/../android-sdk
                        export PATH=$PATH:$ANDROID_HOME/platform-tools
                        export PATH=$PATH:$ANDROID_HOME/build-tools/30.0.3
                        flutter pub get
                        flutter build apk
                    '''
                }
            }
        }
    }
}
