// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX6gb6znrz1k3GWbUz3wHyo9TgmBehlCM',
    appId: '1:876598819894:android:96a70209fc5fb90fd3ac97',
    messagingSenderId: '876598819894',
    projectId: 'quizlearnappai',
    databaseURL: 'https://quizlearnappai-default-rtdb.firebaseio.com',
    storageBucket: 'quizlearnappai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiPPvgj4ib17sumFUDsYaudyWt1UALvqE',
    appId: '1:876598819894:ios:ae6cdcad883dda07d3ac97',
    messagingSenderId: '876598819894',
    projectId: 'quizlearnappai',
    databaseURL: 'https://quizlearnappai-default-rtdb.firebaseio.com',
    storageBucket: 'quizlearnappai.appspot.com',
    androidClientId: '876598819894-hjvg4dmrc61e3rvbc435pl0bp9lc7cf3.apps.googleusercontent.com',
    iosClientId: '876598819894-vi4mifg2697ur1l9oslmjtp9njlept4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizLearnAppAi',
  );
}
